[package]
name = "miniter-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Audio decoding, probe, and mixing."

[dependencies]
miniter-domain.workspace = true
symphonia = { workspace = true, features = [
    "aac",
    "alac",
    "flac",
    "mpa",
    "vorbis",
    "isomp4",
    "mkv",
    "ogg",
    "wav",
] }
symphonia-adapter-oporus.workspace = true
thiserror.workspace = true
log.workspace = true
