[workspace]
resolver = "2"
members = [
    "crates/miniter-domain",
    "crates/miniter-usecases",
    "crates/miniter-render-plan",
    "crates/miniter-audio",
    "crates/miniter-media-native",
    "crates/miniter-ffi",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/mlm-games/Miniter"
description = "timeline, media, and render plan crates"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde", "js"] }
thiserror = "2"
log = "0.4"
anyhow = "1"
web-time = "1.1.0"

uniffi = { version = "0.32", features = ["wasm-unstable-single-threaded"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
getrandom = { version = "0.4", features = ["wasm_js"] }

symphonia = "0.6"
symphonia-adapter-oporus = "0.1.3"
oporus = "0.2.4"
ivf = "0.1"
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "webp",
    "gif",
    "bmp",
    "tiff",
] }
fontdue = "0.9"

baabaabaabaabababbababbaa = { git = "https://github.com/mlm-games/baa4bababab2baa", package = "baabaabaabaabababbababbaa" }
ass-renderer = { git = "https://github.com/mlm-games/ass-rs", package = "ass-renderer", default-features = false }
ass-core = { git = "https://github.com/mlm-games/ass-rs", package = "ass-core" }

miniter-domain = { path = "crates/miniter-domain", version = "0.1.0" }
miniter-usecases = { path = "crates/miniter-usecases", version = "0.1.0" }
miniter-render-plan = { path = "crates/miniter-render-plan", version = "0.1.0" }
miniter-audio = { path = "crates/miniter-audio", version = "0.1.0" }
miniter-media-native = { path = "crates/miniter-media-native", version = "0.1.0" }
miniter-ffi = { path = "crates/miniter-ffi", version = "0.1.0" }

[patch.crates-io]
muxide = { git = "https://github.com/mlm-games/muxide" }
videoson = { git = "https://github.com/mlm-games/videoson" }

symphonia-core = { git = "https://github.com/mlm-games/symphonia", package = "symphonia-core" }
symphonia-format-mkv = { git = "https://github.com/mlm-games/symphonia", package = "symphonia-format-mkv" }
symphonia-format-isomp4 = { git = "https://github.com/mlm-games/symphonia", package = "symphonia-format-isomp4" }

# baabaabaabaabababbababbaa = { path = "../../../Documents/Repos/baa4bababab2baa", package = "baabaabaabaabababbababbaa" }
# muxide = { path = "../../../Documents/Repos/muxide" }
# videoson = { path = "../../../Documents/Repos/videoson/videoson", package = "videoson" }
# ass-renderer = { path = "../../../Documents/Repos/ass-rs/crates/ass-renderer" }
# ass-core = { path = "../../../Documents/Repos/ass-rs/crates/ass-core" }
# symphonia = { path = "../../../Documents/Repos/symphonia/symphonia" }

[profile.release] # for fdroid
opt-level = 3
lto = "fat"
codegen-units = 1
