[package]
name = "miniter-usecases"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Use-cases and reducers domain."

[dependencies]
miniter-domain.workspace = true
serde.workspace = true
uuid.workspace = true
thiserror.workspace = true
log.workspace = true
